# Alert application properties

spring:
    cassandra:
        contact-points: cassandra
        port: 9042
        local-datacenter: datacenter1
        schema-action: create_if_not_exists
    data:
        redis:
            host: redis
            port: 6379