# Global application properties

spring:
    loadbalancer:
        ribbon:
            enabled: false
    data:
        mongodb:
            uri: mongodb://user:pass@mongo:27017/minisocialdb?authSource=admin
            database: minisocialdb
        redis:
            host: redis
            port: 6379

logging:
    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{0}: %msg%n"

server:
    port: ${SERVER_PORT:8181}

user:
    graphql:
        baseUrl: "http://user/graphql"
    restapi:
        baseUrl: "http://user/restapi"

post:
    graphql:
        baseUrl: "http://post/graphql"
    restapi:
        baseUrl: "http://post/restapi"

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
            show-components: always
    tracing:
        enabled: true
        sampling:
            probability: 1.0
    zipkin:
        tracing:
            endpoint: http://zipkin:9411/api/v2/spans
