# Ingestion application properties

spring:
    cassandra:
        contact-points: localhost
        port: 9042
        local-datacenter: datacenter1
        schema-action: create_if_not_exists
    data:
        redis:
            host: localhost
            port: 6379