# Monitoring application properties

spring:
    data:
        redis:
            host: redis
            port: 6379

monitoring:
    blood-pressure:
        max-value:
            systolic: 120
            diastolic: 80
        min-value:
            systolic: 90
            diastolic: 60
    heart-rate:
        max-value: 100
        min-value: 60
    oxygen-saturation:
        max-value: 100
        min-value: 95
