# Order application properties - Choreography profile

spring:
    cloud:
        function:
            definition: publishOrderEvent;processProductEvent;processPaymentEvent;processShippingEvent
        stream:
            bindings:

                publishOrderEvent-out-0:
                    destination: order-events
                
                processProductEvent-in-0:
                    destination: product-events
                    group: order-service-group
                    consumer:
                        spring.json.value.default.type: br.edu.ufrn.order.saga.choreography.event.Event
                        spring.json.trusted.packages: br.edu.ufrn.order.saga.choreography.event

                processProductEvent-out-0:
                    destination: order-events

                processPaymentEvent-in-0:
                    destination: payment-events
                    group: order-service-group
                    consumer:
                        spring.json.value.default.type: br.edu.ufrn.order.saga.choreography.event.Event
                        spring.json.trusted.packages: br.edu.ufrn.order.saga.choreography.event

                processPaymentEvent-out-0:
                    destination: order-events

                processShippingEvent-in-0:
                    destination: shipping-events
                    group: order-service-group
                    consumer:
                        spring.json.value.default.type: br.edu.ufrn.order.saga.choreography.event.Event
                        spring.json.trusted.packages: br.edu.ufrn.order.saga.choreography.event

                processShippingEvent-out-0:
                    destination: order-events
            