# Order application properties - Orchestration profile

spring:
    cloud:
        function:
            definition: processOrderCommand;sinkEvent
        stream:
            bindings:
                processOrderCommand-in-0:
                    destination: order_commands
                processOrderCommand-out-0:
                    destination: saga_events
                sinkEvent-in-0:
                    destination: saga_events
                send-order-command-out-0:
                    destination: order_commands
                send-product-command-out-0:
                    destination: product_commands
                send-payment-command-out-0:
                    destination: payment_commands
                send-shipping-command-out-0:
                    destination: shipping_commands
            