# Payment application properties - Choreography profile

spring:
    cloud:
        function:
            definition: processProductEvent;processShippingEvent
        stream:
            bindings:

                processProductEvent-in-0:
                    destination: product-events
                    group: payment-service-group
                    content-type: application/json
                    consumer:
                        # spring.json.value.default.type: br.edu.ufrn.payment.saga.choreography.event.Event
                        spring.json.trusted.packages: br.edu.ufrn.payment.saga.choreography.event
                        spring.json.add.type.headers: true
                        spring.json.use.type.headers: true

                processProductEvent-out-0:
                    destination: payment-events

                processShippingEvent-in-0:
                    destination: shipping-events
                    group: payment-service-group
                    content-type: application/json
                    consumer:
                        # spring.json.value.default.type: br.edu.ufrn.payment.saga.choreography.event.Event
                        spring.json.trusted.packages: br.edu.ufrn.payment.saga.choreography.event
                        spring.json.add.type.headers: true
                        spring.json.use.type.headers: true

                processShippingEvent-out-0:
                    destination: payment-events
            