# Payment application properties - Orchestration profile

spring:
    cloud:
        function:
            definition: processPaymentCommand
        stream:
            bindings:
                processPaymentCommand-in-0:
                    destination: payment_commands
                    group: payment-service
                processPaymentCommand-out-0:
                    destination: saga_events
                    group: payment-service
