# Product application properties - Choreography profile

spring:
    cloud:
        function:
            definition: processOrderEvent;processPaymentEvent;processShippingEvent
        stream:
            bindings:

                processOrderEvent-in-0:
                    destination: order-events
                    group: product-service-group
                    consumer:
                        spring.json.value.default.type: br.edu.ufrn.product.saga.choreography.event.OrderEvent
                        spring.json.trusted.packages: br.edu.ufrn.product.saga.choreography.event

                processOrderEvent-out-0:
                    destination: product-events

                processPaymentEvent-in-0:
                    destination: payment-events
                    group: product-service-group
                    consumer:
                        spring.json.value.default.type: br.edu.ufrn.product.saga.choreography.event.PaymentEvent
                        spring.json.trusted.packages: br.edu.ufrn.product.saga.choreography.event

                processPaymentEvent-out-0:
                    destination: product-events

                processShippingEvent-in-0:
                    destination: shipping-events
                    group: product-service-group
                    consumer:
                        spring.json.value.default.type: br.edu.ufrn.product.saga.choreography.event.ShippingEvent
                        spring.json.trusted.packages: br.edu.ufrn.product.saga.choreography.event

                processShippingEvent-out-0:
                    destination: product-events
            