# Product application properties - Choreography profile

spring:
    cloud:
        function:
            definition: processOrderEvent;processPaymentEvent;processShippingEvent
        stream:
            bindings:

                processOrderEvent-in-0:
                    destination: order-events
                    group: product-service-group
                    content-type: application/json
                    consumer:
                        # spring.json.value.default.type: br.edu.ufrn.product.saga.choreography.event.Event
                        spring.json.trusted.packages: br.edu.ufrn.product.saga.choreography.event
                        spring.json.add.type.headers: true
                        spring.json.use.type.headers: true

                processOrderEvent-out-0:
                    destination: product-events

                processPaymentEvent-in-0:
                    destination: payment-events
                    group: product-service-group
                    content-type: application/json
                    consumer:
                        # spring.json.value.default.type: br.edu.ufrn.product.saga.choreography.event.Event
                        spring.json.trusted.packages: br.edu.ufrn.product.saga.choreography.event
                        spring.json.add.type.headers: true
                        spring.json.use.type.headers: true

                processPaymentEvent-out-0:
                    destination: product-events

                processShippingEvent-in-0:
                    destination: shipping-events
                    group: product-service-group
                    content-type: application/json
                    consumer:
                        # spring.json.value.default.type: br.edu.ufrn.product.saga.choreography.event.Event
                        spring.json.trusted.packages: br.edu.ufrn.product.saga.choreography.event
                        spring.json.add.type.headers: true
                        spring.json.use.type.headers: true

                processShippingEvent-out-0:
                    destination: product-events
            