# Shipping application properties - Choreography profile

spring:
    cloud:
        function:
            definition: processPaymentEvent
        stream:
            bindings:

                processPaymentEvent-in-0:
                    destination: payment-events
                    group: shipping-service-group
                    content-type: application/json
                    consumer:
                        spring.json.value.default.type: br.edu.ufrn.shipping.saga.choreography.event.PaymentEvent
                        spring.json.trusted.packages: br.edu.ufrn.shipping.saga.choreography.event
                        spring.json.add.type.headers: true
                        spring.json.use.type.headers: true

                processPaymentEvent-out-0:
                    destination: shipping-events
            