# Shipping application properties - Orchestration profile

spring:
    cloud:
        function:
            definition: processShippingCommand
        stream:
            bindings:
                processShippingCommand-in-0:
                    destination: shipping_commands
                    group: shipping-service
                processShippingCommand-out-0:
                    destination: saga_events
                    group: shipping-service